// OtterAgent interfaces
export type {
	AgentEnvironment,
	AuthStorage,
	EntryId,
	ReadonlySessionManager,
	SessionContext,
	SessionManager,
	ToolDefinition,
	UIProvider,
} from "./interfaces/index.js";
export { noOpUIProvider } from "./interfaces/ui.js";

// ExtensionsAPI
export type {
	AgentEndEvent,
	AgentStartEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	CommandInfo,
	CommandOptions,
	CompactOptions,
	ContextEvent,
	ContextEventResult,
	ContextUsage,
	EventBus,
	Extension,
	ExtensionCommandContext,
	ExtensionContext,
	ExtensionEvent,
	ExtensionEventName,
	ExtensionHandler,
	ExtensionRunnerActions,
	ExtensionsAPI,
	InputEvent,
	InputEventResult,
	InputSource,
	MessageEndEvent,
	MessageStartEvent,
	MessageUpdateEvent,
	ProviderConfig,
	ProviderModelConfig,
	SessionBeforeCompactEvent,
	SessionBeforeCompactResult,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	ToolCallEvent,
	ToolCallEventResult,
	ToolExecutionEndEvent,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolResultEvent,
	ToolResultEventResult,
	TurnEndEvent,
	TurnStartEvent,
} from "./extensions/index.js";
export { createEventBus, ExtensionRunner } from "./extensions/index.js";

// AgentSession
export {
	AgentSession,
	buildSystemPrompt,
	buildToolSection,
	convertToLlm,
	createAgentSession,
	createCompactionSummaryMessage,
	createCustomMessage,
	ModelRegistry,
	wrapToolDefinition,
} from "./session/index.js";
export type {
	AgentSessionEvent,
	AgentSessionOptions,
	BuildSystemPromptOptions,
	CompactionSummaryMessage,
	CreateAgentSessionResult,
	CustomMessage,
} from "./session/index.js";

// RPC handler
export { RpcHandler, createRpcUIProvider } from "./rpc/index.js";
export type { RpcHandlerOptions } from "./rpc/index.js";

// RPC protocol
export type {
	AbortCommand,
	CompactCommand,
	ExtensionUIConfirmRequest,
	ExtensionUIDialogRequest,
	ExtensionUIInputRequest,
	ExtensionUINotifyRequest,
	ExtensionUIRequest,
	ExtensionUIResponse,
	ExtensionUISelectRequest,
	FollowUpCommand,
	GetCommandsCommand,
	GetStateCommand,
	PromptCommand,
	RpcAgentEvent,
	RpcAgentEventName,
	RpcCommand,
	RpcCommandInfo,
	RpcCommandType,
	RpcErrorResponse,
	RpcExtensionEventName,
	RpcGetCommandsData,
	RpcInboundMessage,
	RpcOutboundMessage,
	RpcResponse,
	RpcResponseDataFor,
	RpcSessionState,
	RpcSetModelData,
	RpcSuccessResponse,
	RpcTransport,
	SetModelCommand,
	SetThinkingLevelCommand,
	SteerCommand,
} from "./rpc/index.js";
